# Numpy Basics <hr style="boarder:2.5px solid #Ffc0cb"></hr>

Data Analyst: Dale Christian G. Sumugat <br>
Department: Electrical Engineering

In [52]:
# imports and packages
import numpy as np
from scipy import stats

# 1D Array

In [53]:
array_a = np.array ([1, 2, 3])
array_a

array([1, 2, 3])

# 2D Array 

In [54]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
my_array = my_array.T
my_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [56]:
my_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [57]:
np.sum(my_array, axis=0)

array([ 6, 15])

In [58]:
np.sum(my_array,axis=1)

array([5, 7, 9])

# Measures of Central Tendency

In [59]:
fruits = np.array([120, 60, 85, 150, 200])
fruits

array([120,  60,  85, 150, 200])

In [60]:
fruits_mean = np.mean(fruits)
fruits_mean

123.0

In [61]:
median_fruits = np.median(fruits)
median_fruits

120.0

In [62]:
mode_fruits = stats.mode(fruits)
mode_fruits

ModeResult(mode=60, count=1)

# Jaguar Vs Panther

## Jaguar

In [63]:
jaguar = np.array([10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8])
jaguar

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [64]:
jaguar_mean = np.mean(jaguar)
jaguar_mean

9.399999999999999

In [65]:
median_jaguar = np.median(jaguar)
median_jaguar

9.8

In [66]:
mode_jaguar = stats.mode(jaguar)
mode_jaguar

ModeResult(mode=9.8, count=2)

In [67]:
max_jaguar = np.max(jaguar)
min_jaguar = np.min(jaguar)

range_jaguar =max_jaguar - min_jaguar
range_jaguar

8.0

In [68]:
# Q1
q1_jag = np.percentile(jaguar, 25)
q1_jag

9.4

In [75]:
# Q2 MEDIAN
q2_jag = np.percentile(jaguar, 50)
q2_jag

9.8

In [70]:
# Q3
q3_jag = np.percentile(jaguar, 75)
q3_jag

10.45

In [76]:
#IQR
iqr_jag = q3_jag - q1_jag
iqr_jag

1.049999999999999

In [77]:
# sample variance
var_jag = np.var(jaguar,ddof=1)
var_jag

4.86

In [78]:
# sample standard deviation
std_jag = np.std(jaguar,ddof=1)
std_jag

2.2045407685048604

## Panther

In [71]:
panther = np.array([10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1])
panther

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1])

In [72]:
panther_mean = np.mean(panther)
panther_mean

10.75

In [73]:
median_panther = np.median(panther)
median_panther

9.55

In [74]:
mode_panther = stats.mode(panther)
mode_panther

ModeResult(mode=9.1, count=3)

In [79]:
max_panther = np.max(panther)
min_panther = np.min(panther)

range_panther =max_panther - min_panther
range_panther

10.9

In [80]:
# Q1
q1_panther = np.percentile(panther, 25)
q1_panther

9.125

In [81]:
# Q2 MEDIAN
q2_panther = np.percentile(panther, 50)
q2_panther

9.55

In [82]:
# Q3
q3_panther = np.percentile(panther, 75)
q3_panther

10.625

In [83]:
#IQR
iqr_panther = q3_panther - q1_panther
iqr_panther

1.5

In [84]:
# sample variance
var_panther = np.var(panther,ddof=1)
var_panther

11.082777777777777

In [ ]:
# sample standard deviation
std_panther = np.std(panther,ddof=1)
std_panther